ci/cd pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,17 +27,25 @@ jobs:
 
       - name: Run Unit Test and collect coverage
         run: npm run test:cov
-      - name: Check coverage
-        run: |
-              COVERAGE=$(cat coverage/coverage-final.json | jq .total.lines.pct)
-              echo "Coverage: $COVERAGE%"
-              if (( $(echo "$COVERAGE < 80" | bc -l) )); then
-                echo "Coverage is below 80%. Aborting deployment."
-                exit 1
-              fi
+
+      - name: Check coverage threshold
+        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          threshold: 80
+      - name: Debug coverage directory
+        run: ls -R coverage
+     
+      #   - name: Check coverage
+      #     run: |
+      #           COVERAGE=$(cat coverage/coverage-final.json | jq .total.lines.pct)
+      #           echo "Coverage: $COVERAGE%"
+      #           if (( $(echo "$COVERAGE < 80" | bc -l) )); then
+      #             echo "Coverage is below 80%. Aborting deployment."
+      #             exit 1
+      #           fi
       - name: Run E2E tests
         run: npm run test:e2e
-        
 
   # sonarqube:
   #   runs-on: ubuntu-latest
@@ -53,20 +61,16 @@ jobs:
   #         java-version: '17'
   #         distribution: 'temurin'
 
-      # - name: SonarQube Scan
-      #   env:
-      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      #   run: |
-      #     npm install sonar-scanner --save-dev
-      #     npx sonar-scanner \
-      #       -Dsonar.projectKey=your-project-key \
-      #       -Dsonar.organization=your-organization \
-      #       -Dsonar.host.url=https://sonarcloud.io \
-      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
-
-
-
-
+  # - name: SonarQube Scan
+  #   env:
+  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #   run: |
+  #     npm install sonar-scanner --save-dev
+  #     npx sonar-scanner \
+  #       -Dsonar.projectKey=your-project-key \
+  #       -Dsonar.organization=your-organization \
+  #       -Dsonar.host.url=https://sonarcloud.io \
+  #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
   # build:
   #   runs-on: ubuntu-latest
